WID 848 Modal Improvement
sezzle/sezzle-js pull request #1071
Opened 2022-04-26 19:39 UTC by gopida

2022-04-28 13:11 UTC, aholdahl commented on modals/modals-3.0.4/modal-standard.js
> +        return `<div class="sezzle-checkout-modal-hidden">
In LT version, you've removed this tag layer. I see in modal.js that you are assigning class name to sezzle-modal-container, so I believe this is the one that needs updated?

2022-04-28 19:36 UTC, gopida commented on modals/modals-3.0.4/modal-standard.js
> +        return `<div class="sezzle-checkout-modal-hidden">
yes thanks, updated

2022-04-28 19:38 UTC, gopida commented on modals/index.html
> +        <button tabIndex="0" aria-label="Close Sezzle Modal" class="close-sezzle-modal" role="button"></button>
This file is only for local testing. And we have only restructured the divs here, so this won't couple modal and js.

2022-04-28 19:41 UTC, gopida commented on gulpfile.js
> +gulp.task('buildmodal', gulp.series('cleanmodal', 'csscompile-modal', 'minify-js', 'minify-modal'));
Yes, added this gulp command to build modal locally. `npx gulp buildmodal` will build the modal in `dist` dir.

2022-04-29 13:17 UTC, aholdahl requested changes

2022-04-29 13:17 UTC, aholdahl commented on modals/index.html
> +    <div class="sezzle-modal">
Sorry, just noticed how different this is from the original - missing containers/class names, and button/logo are switched. Based on the original layout, it should be:
```
<div id="sezzle-modal-container">
	<div class="sezzle-checkout-modal-hidden">
		<div class="sezzle-modal">
			<div class="sezzle-modal-content" tabIndex="0">
				<div class="sezzle-logo" title="Sezzle"> </div>
				<button aria-label="Close Sezzle Modal" class="close-sezzle-modal" role="button"></button>
				<div id="sezzle-modal-core-content" class="sezzle-modal-content"></div>
			</div>
		</div>
	</div>
</div>
```

2022-04-29 15:56 UTC, aholdahl approved these changes

2022-04-29 15:56 UTC, merged