MINT-24:removing deprecated widget options
sezzle/sezzle-js pull request #1080
Opened 2022-05-02 20:42 UTC by sitikanthasezzle

MINT-24:removing deprecated widget options

2022-05-05 17:53 UTC, hardikk08 commented on src/classBased/payment/priceProcessor.js
> +        widgetPriceValue = (price.value / 4).toFixed(this.#numberOfDecimals);
would be a good idea to create a variable in the constructor instead of hard coding here

2022-05-06 21:02 UTC, aholdahl commented on src/classBased/payment/priceProcessor.js
> +        widgetPriceValue = (price.value / 4).toFixed(this.#numberOfDecimals);
Agreed - let's revert this line, and allow it to pull as before here.

2022-05-09 17:11 UTC, aholdahl commented on src/classBased/widgetRenderer.js
> -          logoNode.src = configGroup.imageURL;
I suspect this line is still needed, it is just assigned through `theme`. Did you test this locally?

2022-05-09 20:47 UTC, sitikanthasezzle commented on src/classBased/payment/priceProcessor.js
> +        widgetPriceValue = (price.value / 4).toFixed(this.#numberOfDecimals);
resolved the issues by reverting line to original

2022-05-09 20:47 UTC, sitikanthasezzle commented on src/classBased/sezzle-init.js
> -    const widgetEventLogger = WidgetEventLogger.NewWidgetEventLogger(document.sezzleConfig.merchantID, document.sezzleConfig.noTracking);
resolved the issues by reverting line to original

2022-05-09 20:47 UTC, sitikanthasezzle commented on src/classBased/widgetRenderer.js
> -          logoNode.src = configGroup.imageURL;
resolved the issues by reverting the line to original

2022-05-10 13:55 UTC, aholdahl requested changes

2022-05-10 13:55 UTC, aholdahl commented on modals/modals-2.0.8/modal.scss
> +.sezzle-payment-pie-only {
You don't need to make changes in 2.0.8, because that is EU version, and since they are going away, this version will be decommissioned.

2022-05-10 13:55 UTC, aholdahl commented on modals/modals-3.0.1/modal-en.html
> +                <div class="sezzle-payment-pie-only"></div>
If you change the class-name here, you need to change it in the accompanying css file. Since 3.0.1 doesn't actually support DE translation, I don't think we need changes in this version.

2022-05-10 13:55 UTC, aholdahl commented on modals/modals-3.0.2/modal-standard.js
> +                  <div class="sezzle-modal sezzle-modal-color"}">
Typo here `"}`

2022-05-10 13:55 UTC, aholdahl commented on modals/modals-3.0.2/modal.js
>  function getStandardModal(language, theme) {
Need to remove theme from params here

2022-05-10 13:55 UTC, aholdahl commented on modals/modals-3.0.3/modal-standard.js
> +                  <div class="sezzle-modal sezzle-modal">
Class name should be "sezzle-modal sezzle-modal-color" here

2022-05-10 13:55 UTC, aholdahl commented on src/classBased/utils.js
> +    return Utils.getWidgetBaseUrl() === ['US', 'CA', 'IN', 'GU', 'PR', 'VI', 'AS', 'MP'];
This should just be the array - remove `Utils.getWidgetBaseUrl() ===`

2022-05-10 13:55 UTC, aholdahl commented on src/classBased/widgetConfiguration.test.js
> -  test('Throws an error when a property which does not belong to a config group is being defined in a config group', () => {
I don't think you need to remove this test...

2022-05-10 13:55 UTC, aholdahl commented on src/classBased/widgetRenderer.js
> -            const widgetEventLogger = WidgetEventLogger.NewWidgetEventLogger(document.sezzleConfig.merchantID, document.sezzleConfig.noTracking);
Please undo changes on this line.

2022-05-10 13:55 UTC, aholdahl commented on src/helper.js
> +    b) white
Instead of grayscale and white, it is black-flat and white-flat

2022-05-10 13:55 UTC, aholdahl commented on src/helper.js
> - * @param {Number} numberOfPayments
Add this line back.

2022-05-10 13:55 UTC, aholdahl commented on src/sezzle.js
> -  // no gtm
Add back these lines

2022-05-10 17:57 UTC, sitikanthasezzle commented on modals/modals-2.0.8/modal.scss
> +.sezzle-payment-pie-only {
resolved the issues by reverting the line to original

2022-05-10 17:57 UTC, sitikanthasezzle commented on modals/modals-3.0.1/modal-en.html
> +                <div class="sezzle-payment-pie-only"></div>
resolved the issues by reverting the line to original

2022-05-10 17:57 UTC, sitikanthasezzle commented on modals/modals-3.0.2/modal-standard.js
> +                  <div class="sezzle-modal sezzle-modal-color"}">
removed "}

2022-05-10 17:57 UTC, sitikanthasezzle commented on modals/modals-3.0.2/modal.js
>  function getStandardModal(language, theme) {
theme params is removed

2022-05-10 19:00 UTC, aholdahl commented on src/classBased/payment/priceProcessor.test.js
> +  let widgetConfig = {
I was having some trouble with tests failing when trying to remove numberOfPayments. Will do a separate MR to experiment with cleaning this up.

2022-05-10 19:12 UTC, aholdahl approved these changes

2022-05-10 20:06 UTC, merged