MINT-15 Render widget even when price is less than min price
sezzle/sezzle-js pull request #1087
Opened 2022-05-13 22:10 UTC by gopida

2022-05-17 14:53 UTC, aholdahl requested changes
Don't forget to update the widget-options.md entry!

2022-05-17 20:11 UTC, aholdahl requested changes

2022-05-17 20:11 UTC, aholdahl commented on widget-options.md
> +**Purpose**: Minimum price in cents for which the widget should be rendered. If the price at `targetXPath` is lower than this number, the widget will render with a note stating the minimum eligible p
Purpose and Additional Details still need further updates.

Minimum price in cents for which Sezzle can be selected at checkout.

Remove `While Sezzle is not advertised on these items`

2022-05-17 20:11 UTC, aholdahl commented on widget-options.md
> +**Purpose**: Minimum price in cents for which the widget should be rendered. If the price at `targetXPath` is lower than this number, the widget will render with a note stating the minimum eligible p
Oh, also add this change to the upcoming version in CHANGELOG.md

2022-05-17 20:58 UTC, gopida commented on widget-options.md
> +**Purpose**: Minimum price in cents for which the widget should be rendered. If the price at `targetXPath` is lower than this number, the widget will render with a note stating the minimum eligible p
Ahh... I keep forgetting that. Thank you. Addressed both.

2022-05-18 13:08 UTC, aholdahl approved these changes

2022-05-18 13:09 UTC, merged