Mint 264 update gulp
sezzle/sezzle-js pull request #1159
Opened 2022-10-24 20:55 UTC by aholdahl

2022-10-24 21:03 UTC, aholdahl commented
This MR is to clean up the code by renaming variables to be clear and consistent, dry up some repetitive functions, and re-order the contents so hopefully it's easier to navigate. I was able to test all of the release series'.

The MR does not yet solve the clunky release process, but it will give us a cleaner codebase to work on.

2022-10-25 21:23 UTC, gopida requested changes

2022-10-25 21:23 UTC, gopida commented on gulpfile.mjs
> +task('deploymodal', series('deployupdatemodal', parallel('post-modal-version')));
Deploy tasks are erroring out and looks like the tasks in series needs a callback().

On executing npx gulp deploymodal
```
The following tasks did not complete: deploymodal, deployupdatemodal, minify-modal-css
[17:18:22] Did you forget to signal async completion?
```

Looking into possible solutions, but if you already know how to fix it 👍

2022-10-26 13:58 UTC, aholdahl commented on gulpfile.mjs
> +task('deploymodal', series('deployupdatemodal', parallel('post-modal-version')));
https://gulpjs.com/docs/en/getting-started/async-completion/

In this gulpfile, all tasks are either escaped with a callback function `done()` or by returning a stream.

2022-10-26 15:00 UTC, gopida approved these changes

2022-10-26 18:01 UTC, merged