Implement de and en for EU widget copy
sezzle/sezzle-js pull request #845
Opened 2021-03-15 17:13 UTC by the-bionic

EUDEV-506.

Implement new translations for English and German copies.
![image](https://user-images.githubusercontent.com/22380117/111193092-16ed6500-85ba-11eb-9e04-2895a00ba7eb.png)

![image](https://user-images.githubusercontent.com/22380117/111193162-2a98cb80-85ba-11eb-8220-aca34b5cc43f.png)

2021-03-16 08:44 UTC, anubhav-sri commented on src/classBased/sezzleConfig.js
>        fr: `ou ${this.sezzleConfig.numberOfPayments} paiements de %%price%% sans intérêts avec %%logo%% %%info%%`,
no changes in french translation?

2021-03-19 14:27 UTC, aholdahl requested changes

2021-03-19 14:27 UTC, aholdahl commented on src/classBased/sezzleDOMFunctions.js
> +    // for EU we want the format {price}(Euros symbol) as opposed to ${price} for North America
@the-bionic this is not a necessary step. '{price}' replaces the number+delimiter string from the targetXPath.textContent, therefore any words or symbols (including currency) retain their original place in the formatter so the widget matches the original format from the targetXPath. Even so, the function that follows would not have the desired effect - it would remove the installment amount from the widget but would still include the NaN text. `or 4 times € EUR with Sezzle - no fee`

2021-03-19 14:27 UTC, aholdahl commented on src/classBased/utils.js
> +  static isSupportedEULocale(userLocale = navigator.language || navigator.browserLanguage || '') {
We have existing `checkIfLanguageIsValid` function that, in the current format, loops through the translations object. This could be reformatted to handle EU language in the same way, so we don't need to maintain a separate array.

2021-03-22 18:58 UTC, aholdahl commented on src/classBased/sezzleDOMFunctions.js
> +    // for EU we want the format {price}(Euros symbol) as opposed to ${price} for North America
I missed that you were prepending the pricePlaceholder ahead of the formatter without it. So you want the currency symbol to always show after the amount, regardless of how the merchant displays the price? 

Looks like this change was removed, so please confirm if we can consider this resolved.

2021-03-22 19:05 UTC, aholdahl approved these changes

2021-03-22 19:12 UTC, merged