after adding a new modal for EU team, added competitor widget trackin…
sezzle/sezzle-js pull request #862
Opened 2021-04-01 13:38 UTC by dhruv1794

…g WID-369

2021-04-01 15:56 UTC, aholdahl commented on src/classBased/language.js
> +      let coreLang = lang.split('-')[0].substring(0,2).toLowerCase();;
there are double semicolons here

2021-04-01 15:58 UTC, aholdahl commented on src/classBased/language.js
> +        console.log(langVar)
Remove console.log ahead of launch unless it should communicate an error to the merchant.

2021-04-01 16:11 UTC, aholdahl requested changes

2021-04-01 16:11 UTC, aholdahl commented on src/classBased/language.js
> +        if(northAmericaRegion.indexOf(locale) > -1){
This does not consider IP location, which we discovered was an issue - Sitikantha and Sanjarekha observed in 21.3.1 that their browser language is en-GB, hence they are being served the EU content when they should receive the US content.

2021-04-01 16:11 UTC, aholdahl commented on src/classBased/language.js
> +            let locale = this.getLanguageLocale(lang);
Why would this check happen only on string and not on function?

2021-04-01 16:11 UTC, aholdahl commented on src/classBased/language.js
> +      const coreLang =  lang.split("-")[0]
This would not check validity of EU language options, hence if language was given as es-ES or de-AT, it would return true on this function, but would then fail when getting the translation.

2021-04-01 16:11 UTC, aholdahl commented on src/classBased/modal.js
> +      } else if(document.sezzleDefaultModalVersion === "sezzle-modal-3.0.1-{%%s%%}.html"){
Since sezzleModalToGet is the same template for both, they can both be combined in "if" using OR `||`

2021-04-02 09:11 UTC, dhruv1794 commented on src/classBased/language.js
> +      let coreLang = lang.split('-')[0].substring(0,2).toLowerCase();;
Resolved.

2021-04-02 09:11 UTC, dhruv1794 commented on src/classBased/language.js
> +        console.log(langVar)
resolved.

2021-04-09 13:29 UTC, dhruv1794 commented on src/classBased/language.js
> +        if(northAmericaRegion.indexOf(locale) > -1){
fixed this in latest MR

2021-04-09 13:30 UTC, dhruv1794 commented on src/classBased/language.js
> +            let locale = this.getLanguageLocale(lang);
Fixed this in latest MR.

2021-04-09 13:30 UTC, dhruv1794 commented on src/classBased/language.js
> +      const coreLang =  lang.split("-")[0]
Fixed this in latest MR

2021-04-13 14:04 UTC, aholdahl requested changes

2021-04-14 10:59 UTC, dhruv1794 commented on modals/index.js
> +  link.href = theme === 'grayscale' ? `modals-${process.env.VERSION}/modal_grayscale.scss`:`modals-${process.env.VERSION}/modal.scss`
Resolved this in latest MR.

2021-04-14 11:03 UTC, dhruv1794 commented on src/classBased/utils.js
> +    return hsp>127.5 ? 'light' : 'dark';
Fixed this in latest MR.

2021-04-14 11:10 UTC, dhruv1794 commented on src/classBased/sezzleConfig.js
> +    document.sezzleModalTheme = modifiedSezzleConfig.modalTheme;
`document.sezzleModalTheme` is used in `sezzle-js/modals/index.js` (line number 6). 
This is one reasonable way to share data between `src/classBased/sezzleConfig.js` and `sezzle-js/modals/index.js`.
Only negative is that it will overwrite `document.sezzleModalTheme` attributte on DOM (there is very less chance that merchant has such an variable declared on the document obect.

2021-04-14 11:23 UTC, dhruv1794 commented on src/classBased/sezzleConfig.js
> +      'modalTheme',
Added in latest MR.

2021-04-14 12:20 UTC, dhruv1794 commented on src/classBased/language.js
> +    getLanguageLocale(lang){
Your function looks good but there is a tiny flaw. It does not consider lang to be of the type function. My approach was to check for USA first and return EU version otherwise. This is why I save country code and use it to check USA supported Territories. I have changed my approach and used this one instead now with a check for function type in language option.

2021-04-14 12:20 UTC, dhruv1794 commented on src/classBased/sezzle.js
> +    document.sezzleCountryCode  = this._countryCode;
Not necessary with change in approach.

2021-04-14 12:21 UTC, dhruv1794 commented on src/classBased/language.js
> +            language: lang.split("-")[0],
changed the approach. Resolved in latest MR.

2021-04-14 18:20 UTC, aholdahl approved these changes

2021-04-14 18:20 UTC, merged