after fixing transparent background detection
sezzle/sezzle-js pull request #888
Opened 2021-05-06 10:21 UTC by dhruv1794

2021-05-06 13:52 UTC, aholdahl requested changes

2021-05-06 13:52 UTC, aholdahl commented on src/classBased/utils.js
> +    if(color  === 'transparent' || color === 'rgba(0,0,0,0)') {
Zeros need to have spaces between `'rgba(0,0,0,0)' !== 'rgba(0, 0, 0, 0)'`

2021-05-06 13:52 UTC, aholdahl commented on src/classBased/modal.js
> +    if(document.sezzleLanguage !== "en" || document.sezzleLanguage === undefined){
`undefined !== "en"` so what is the purpose of this change?

2021-05-06 13:57 UTC, dhruv1794 commented on src/classBased/utils.js
> +    if(color  === 'transparent' || color === 'rgba(0,0,0,0)') {
no they don't .. I trim the color variable. Both rgba(0,0,0,0) and rgba(0, 0, 0, 0) are equivalent to CSS. I do this incase a merchant puts in body { background: rgba(0,0,0,0) instead of rgba(0, 0, 0, 0)

2021-05-06 13:58 UTC, dhruv1794 commented on src/classBased/modal.js
> +    if(document.sezzleLanguage !== "en" || document.sezzleLanguage === undefined){
Sorry this was done for testing. Have changed this for my next MR for WID-387.

2021-05-10 13:15 UTC, aholdahl approved these changes

2021-05-10 13:15 UTC, merged