WID-551 new modal for sezzle spend
sezzle/sezzle-js pull request #898
Opened 2021-05-26 10:15 UTC by sitikanthasezzle

2021-05-26 13:23 UTC, aholdahl commented on modals/modals-3.0.2/modal-en.html
> +                First-time Sezzle customers will receive $5 in <a onclick="window.open('https://shopper-help.sezzle.com/hc/en-us/articles/360051303312-What-is-Sezzle-Spend-'); return false;" href=""
If you put the URL as the `href` value, then you don't need the `onclick` function.

2021-05-26 13:25 UTC, aholdahl commented on modals/modals-3.0.2/modal-en.html
> +            <div class="mobile sub-feature1" style="color:#352954">
Can we reduce the font here? It would currently receive 18px from the stylesheet, but 14px looks better.

2021-05-26 13:29 UTC, aholdahl requested changes

2021-05-26 13:29 UTC, aholdahl commented on modals/modals-3.0.2/modal-en.html
> +                <div class="desktop">
No need to change margins on corresponding mobile block.

2021-05-26 13:29 UTC, aholdahl commented on modals/modals-3.0.2/modal-en.html
> +            <div class="desktop sub-feature1" style="color:#352954">
On mobile block, font-size should be 12px (currently getting 14px from stylesheet)

2021-05-26 13:31 UTC, aholdahl commented
@sitikanthasezzle Since we are not planning to publish this modal change (at least, not until after the pilot), I don't think Sezzle-JS is the appropriate place for it. I had suggested during the Tuesday stand-up to put the updated code snippet in Confluence since it will only be used internally at this time.

However, I have added comments to the branch for some code changes.

Also note, when using the `altLightboxHTML` config option, we need to copy the modal stylesheet into a <style> element and include in the override.

2021-05-28 17:57 UTC, sitikanthasezzle commented on modals/modals-3.0.2/modal-en.html
> +            <div class="desktop sub-feature1" style="color:#352954">
fixed

2021-05-28 19:12 UTC, aholdahl commented
Weird thing is, most of the changes look like they should solve the issues, but for some reason when I try to test in the static-widgets playground, it isn't getting the new CSS styles. I made some changes in test and saved them in Confluence.

2021-05-28 19:12 UTC, closed without merging