Wid 606 add Sezzle Spend promotion wording to widget and modal
sezzle/sezzle-js pull request #956
Opened 2021-09-14 22:14 UTC by electrodrel

2021-09-15 13:19 UTC, aholdahl requested changes

2021-09-15 13:19 UTC, aholdahl commented on src/classBased/promotion/promotionTranslations.js
> +      let languageText = texts.find(t => t[`${language}`])
Is languageText typeOf string or typeOf array? If array, line 239 should be if languageText.length. If it is a string, line 240 and 243 shouldn't need the key, right?

2021-09-15 13:19 UTC, aholdahl commented on src/classBased/promotion/promotionTranslations.js
> +    return "";
Hmm, I'm wondering about this default... whether it should not show the promo if the correct one isn't found, or if there is a particular combination they would prefer... Making a note as placeholder while reviewing the rest of the code.

2021-09-15 13:19 UTC, aholdahl commented on src/classBased/sezzleConfig.js
> +      let promoText = document.sezzlePromotion ? this.Promotions.getPromotionString() : ""
Since we are storing this in the config above, we could use this.sezzleConfig.promotions instead of document.sezzlePromotion here.

2021-09-15 13:19 UTC, aholdahl commented on src/classBased/sezzleConfig.js
> +      defaultWidgetTemplate = defaultWidgetTemplate.replace("{promotext}", promoText)
This technically works, but per my earlier comment, we could format it like the other placeholders so it is cared for in the switch case directly below here.

2021-09-15 13:19 UTC, aholdahl commented on src/sezzle.config.js
> +exports.promoMinConfig = {
Test suite is failing. Could be just because these haven't been updated to snake case and the new text content, or because I completely screwed up on writing the test itself.

2021-09-15 15:20 UTC, electrodrel commented on CHANGELOG.md
> +- <b>competitor event is firing on every merchant. if block needs .length</b>
I rebased your branch on master, but there were merge conflicts which I probably resolved in favour of your branch. Will take a closer look

2021-09-15 15:37 UTC, electrodrel commented on src/classBased/language.js
> +      en: `or ${this._numberOfPayments} interest-free payments of %%price%%{promotext} with %%logo%% %%info%%`,
Well, the difference between price, log, info and the promotext is that the former have some custom rendering options. As I understand, the switch statement is reserved for that, for example, a separate <div>, a link, etc. Switches are ugly and tend to get larger over time, so if I can get away with a simple `replace` instead of adding another case statement, Id' prefer that. If the requirements are changed, and we need a custom rendering for the promo, we can move it under the rendering function with switches. 

Let me know if there is any other reason you think it'll be better in the rendering function

2021-09-15 15:41 UTC, electrodrel commented on src/classBased/promotion/promotionTranslations.js
> +      let languageText = texts.find(t => t[`${language}`])
`texts` is an array of objects. I check it for nullabilty and not length because I don't access its elements by index, but by `find` function, so I don't need it to have more than 0 element, just not to be null or underfined. 
`languageText` is an object of { "locale" : "text"}. I check its falsiness before trying to access the actual value by the key.

2021-09-15 15:54 UTC, electrodrel commented on src/classBased/sezzleConfig.js
> +      let promoText = document.sezzlePromotion ? this.Promotions.getPromotionString() : ""
`_promoSetter` is not called under the condition of `document.sezzlePromotion` to be present. In the `Promotion` class constructor we also do not check for `document.sezzlePromotion`. So, if no `document.sezzlePromotion` is found in the config, the `Promotion.promoConfig` is null, and `Promotion.getPromotionString()` returns an error. 

That's why we check for `document.sezzlePromotion` every time we call that function (in sezzleConfig and in modal.js)  Checking for `this.sezzleConfig.promotions` wont' give us much, because it's just a reference to a class object that is always created regardless of `document.sezzlePromotion` state.

Probably, the better way is to check if `promoConfig` is null inside the `Promotion.getPromotionString()`  and return empty string if it is. Will update it.

2021-09-15 16:36 UTC, electrodrel commented on src/classBased/modal.js
> +      const modalPromoText = promoString.split('Sezzle Spend'); // ?
If we want our rendering to be agnostic to the name of an umbrella under which a promotion is running (currently, Sezzle Spend), we should include it in the promotion config. That would require sezzle pay to have this field in the first place, so that every promotion is created under a certain promo initiative (together with the hyperlinks and any other additional info.

I can add it into the config on WS part. It will be hardcoded there because sezzle pay doesn't store and doesn't provide this information to us.

To check the length is a good idea! Will update.

2021-09-15 22:14 UTC, electrodrel commented on src/sezzle.config.js
> +exports.promoMinConfig = {
Addressed. I haven't updated the tests to correspond to my updates in the `Promotion` class, that's why they were failing

2021-09-15 22:14 UTC, electrodrel commented on CHANGELOG.md
> +- <b>competitor event is firing on every merchant. if block needs .length</b>
Addressed

2021-09-15 22:15 UTC, electrodrel commented on CHANGELOG.md
> -## v21.6.5 - Released 2 Aug 2021
Addressed

2021-09-15 22:15 UTC, electrodrel commented on package.json
> +  "version": "21.8.4",
Addressed

2021-09-15 22:15 UTC, electrodrel commented on src/classBased/modal.js
> +      const modalPromoText = promoString.split('Sezzle Spend'); // ?
Updated

2021-09-15 22:16 UTC, electrodrel commented on src/classBased/promotion/promotionTranslations.js
> +    return "";
Let me know your thoughts on this

2021-09-15 22:16 UTC, electrodrel commented on src/classBased/sezzleConfig.js
> +      let promoText = document.sezzlePromotion ? this.Promotions.getPromotionString() : ""
Updated

2021-09-16 15:20 UTC, aholdahl submitted a review, later dismissed

2021-09-16 15:20 UTC, aholdahl commented on src/classBased/language.js
> +      en: `or ${this._numberOfPayments} interest-free payments of %%price%%{promotext} with %%logo%% %%info%%`,
Sounds good. I was just aiming for consistency, but I agree with reducing complexity.

2021-09-16 15:20 UTC, aholdahl commented on src/classBased/promotion/promotionTranslations.js
> +                      { "es-ES": "" },
We can use same translation content for "es" and "es-ES" for now.

2021-09-16 15:20 UTC, aholdahl commented on src/classBased/promotion/promotions.test.js
> +  it("when value is integer, no decimals in the final string", () => {
Should this description be updated? "when value is not integer, decimals in the final string"

2021-09-16 15:20 UTC, aholdahl commented on src/classBased/promotion/promotions.test.js
> +    language._language = 'ru';
Looks like here you are testing if language is not supported, defaults to english - should this be included in the test summary?

2021-09-16 15:20 UTC, aholdahl commented on src/sezzle.config.js
> +exports.promoMinConfig = {
Looks like these (promoMinConfig, promoMaxConfig) aren't used with your rewrite of the tests, so they can be removed.

2021-09-16 16:21 UTC, electrodrel commented on src/sezzle.config.js
> +exports.promoMinConfig = {
Addressed

2021-09-16 16:21 UTC, electrodrel commented on src/classBased/promotion/promotionTranslations.js
> +                      { "es-ES": "" },
Addressed

2021-09-16 16:22 UTC, electrodrel commented on src/classBased/promotion/promotions.test.js
> +  it("when value is integer, no decimals in the final string", () => {
It was a copypaste :) Addressed

2021-09-16 16:23 UTC, electrodrel commented on src/classBased/promotion/promotions.test.js
> +    language._language = 'ru';
Fixed

2021-09-17 13:10 UTC, aholdahl commented on src/classBased/promotion/promotionTranslations.js
> +                      { "es-ES": "" },
@electrodrel I am not seeing your changes - can you make sure your push went through? (Also just noticed en-GB is blank, so same principal).

2021-09-20 14:16 UTC, aholdahl approved these changes

2021-09-20 14:17 UTC, aholdahl commented
Just make sure CHANGELOG is updated, and Hardik or I can show you the release process sometime today.

2021-09-20 14:56 UTC, merged