WID-556: add config for custom event listeners
sezzle/sezzle-js pull request #958
Opened 2021-09-21 14:02 UTC by hardikk08

2021-09-22 13:16 UTC, aholdahl requested changes

2021-09-22 13:16 UTC, aholdahl commented on src/classBased/renderAwesomeSezzle.js
> +      console.log(element);
Don't forget to remove console logs before merging to master :)

2021-09-22 13:16 UTC, aholdahl commented on src/classBased/renderAwesomeSezzle.js
> +      const element = document.querySelector(el.element)
What if there are multiples of a certain element? Should we use querySelectorAll so it can accept IDs and classes, then loop through the array to add the listener?

2021-09-22 13:16 UTC, aholdahl commented on src/classBased/renderAwesomeSezzle.js
> +          // let priceElement = document.querySelector('[data-sezzleindex]').getAttribute('data-sezzleindex')
Yes, I believe you would need to removeAttribute('[data-sezzleindex]') as well, but before the init, and as a querySelectorAll and loop, in case of multiple widgets on same page.

2021-09-22 13:16 UTC, aholdahl commented on src/classBased/sezzleDOMFunctions.js
> +    // Will be used later to replace {price} with price / this.numberOfPaym ents Eg: ${price} USD
Guessing this random space was an accident

2021-09-22 14:06 UTC, hardikk08 commented on src/classBased/renderAwesomeSezzle.js
> +      const element = document.querySelector(el.element)
Would there be?

2021-09-22 14:10 UTC, hardikk08 commented on src/classBased/renderAwesomeSezzle.js
> +          // let priceElement = document.querySelector('[data-sezzleindex]').getAttribute('data-sezzleindex')
Yeah, just removed it

2021-09-22 16:12 UTC, aholdahl commented on src/classBased/renderAwesomeSezzle.js
> +      const element = document.querySelector(el.element)
It's possible. Else, we should make it explicit in the documentation, but I think it's better to build for edge cases rather than just happy path. It makes for a better experience using it.

2021-09-23 13:07 UTC, aholdahl commented
I think it looks pretty good, but please update widget-options.md with the new option and instructions for usage. Based on the code, I expect the value is an array of objects, like relatedElementActions, so be sure to mention the required keys.

2021-09-28 12:58 UTC, aholdahl approved these changes

2021-09-28 14:22 UTC, merged