Added new shop checkout events
sezzle/sezzle-js pull request #980
Opened 2021-11-09 16:27 UTC by killianbrackey

Adds new optional event for checkout bypass state

2021-11-09 18:33 UTC, electrodrel requested changes

2021-11-09 18:33 UTC, electrodrel commented on src/classBased/widgetInitializer.js
> +				this.widgetEventLogger.logEvent();
As we don't provide an event name when logging the event, it will be logged as an empty string event name. Widget Server won't be able to process such event as it attaches a specific event handler depending on the event name.

Also, we check the string length twice - inside the utils function and here. I'd suggest removing the utils check and directly calling `utils.getCookie` inside here

2021-11-09 18:33 UTC, electrodrel commented on src/classBased/utils.js
> +			return `shop_checkout_status_${value}`;
the event names follow the naming standard of js event names: it's either one word (onclick, onload) or a dash separated (duplicate-widget).

also, tit seems sezle-js follows camelCase for function names w/o underscores.

2021-11-10 17:34 UTC, killianbrackey commented on src/classBased/widgetInitializer.js
> +				this.widgetEventLogger.logEvent();
I included both checks to reduce a network roundtrip if the data is not found. If there is a better pattern for this let's do it!

2021-11-10 17:34 UTC, killianbrackey commented on src/classBased/utils.js
> +			return `shop_checkout_status_${value}`;
@electrodrel this should be resolved

2021-11-10 18:12 UTC, electrodrel commented on src/classBased/widgetInitializer.js
> +				this.widgetEventLogger.logEvent();
Not sure if it's a better pattern or not, it just seems that the new Utils function logic contains of:
1. getting the cookie value
2. checking if any result is obtained.
3. embed the result if any to the string literal

The widgetInitializer logic is:
1. getting whatever the Utils function returns
2. checking if any result is obtained. 


So, it seems that the actual value of the Utils function is just to get the cookie, because the second check is in the `widgetInitializer`. Taking this into account along with the nature of this event (I assume it will always be logged only once, so no other places we have to repeat this logic), we can just directly call it:

```
const shopCheckoutStatus = Utils._getCookie('shopify_pay_redirect')
  if(shopCheckoutStatus) {
	this.widgetEventLogger.logEvent(`shop-checkout-status-${value}`);
 
```

Not an extremely important change though, but my hope is that with no new function presented, we can save tiny little bit of bundle size with no extra price for readability.

2021-11-11 03:16 UTC, killianbrackey commented on src/classBased/widgetInitializer.js
> +				this.widgetEventLogger.logEvent();
All great points @electrodrel - updated and pushed 👍

2021-11-15 15:49 UTC, killianbrackey commented
@electrodrel - this should be ready to go now!

2021-11-15 16:06 UTC, electrodrel approved these changes

2021-11-15 17:13 UTC, killianbrackey commented
@electrodrel - I added this fix just this morning to include the prefix to the events as they come through: https://github.com/sezzle/sezzle-js/pull/980/commits/c9d4624628c23ffb3fddff1da88f3ed389615a31 Thanks for the approval!

2021-11-15 17:13 UTC, merged