WID 780 - long term lending modal
sezzle/sezzle-js pull request #987
Opened 2021-12-20 21:51 UTC by gopida

I will clean up commented line from gulp after review

2021-12-21 16:19 UTC, hardikk08 commented on modals/modals-3.0.2/modal.js
> +    if(document.longTermPayment){
Maybe worth using ternary operator here?

2021-12-21 16:27 UTC, hardikk08 commented on modals/modals-3.0.2/modal.js
> +    const standardModal = new StandardModal({
we could use shorthand here like: `new StandardModal({language, theme})`

2021-12-21 16:45 UTC, hardikk08 requested changes

2021-12-21 16:45 UTC, hardikk08 commented on modals/language.json
> +  "3.0.2": ["en", "fr", "de", "es"]
@aholdahl  It seems like we are changing the way we are publishing html files with inbuilt translations now. Do we need to maintain this file anymore?

2021-12-21 16:45 UTC, hardikk08 commented on modals/modals-3.0.2/translation.js
> +class Translation {
Might be an overkill to use a class here, we could probably do away with just const or something! What do you think?

2021-12-21 18:22 UTC, gopida commented on modals/language.json
> +  "3.0.2": ["en", "fr", "de", "es"]
This information is passed to WS `/v1/modal/price-widget/version` to maintain the supported language for each version. So we will still have to continue maintaining this info.

2021-12-21 20:11 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    if(document.longTermPayment){
Apart from syntax styling I don't see any advantage using one over the other.

2021-12-21 20:30 UTC, hardikk08 commented on modals/modals-3.0.2/modal.js
> +    if(document.longTermPayment){
Yeah, just a syntax change. I think it would be beneficial to make use of newer es features wherever possible!

2021-12-28 16:09 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    if(document.longTermPayment){
Addressed

2021-12-28 16:09 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    const standardModal = new StandardModal({
Addressed

2021-12-28 16:10 UTC, gopida commented on modals/modals-3.0.2/translation.js
> +class Translation {
Changed it to es6 and added babel. So considering future changes and modularity I think it's better to have it in a class.

2021-12-29 03:08 UTC, electrodrel requested changes
1. Should the modal reload also be added [here](https://github.com/sezzle/sezzle-js/blob/ac6bc8d3b51596f360dbe6aa2e62d1dbda0e704b/src/classBased/sezzleDOMFunctions.js#L255)? As I mentioned before, whenever we update a price in a price range product, we don't re-render the widget, so the `render` function is not called. Instead in the mutation callback (link above) replaces the content of the widget price. We should accordingly replace the modal content.

2. Please, add ; at the end of the sentences in the new codebase you added. This is not obligatory, but it seems to be the pattern in sezzle-js, so better stick to it.

3. I am a bit concerned about the number of adds vs deletions (+1,582 −306), and this is  even without any unit test added. What is the bundle size with all the updates?

2021-12-29 15:55 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    const language = document.modalLanguage || 'en'
`document.modalLanguage` is set in sezzle-js based on the available language option for that particular modal version. It  is defaulted to `en` to handle exceptions(in case `modalLanguage` is not set)

2021-12-29 16:18 UTC, gopida commented
> 1. Should the modal reload also be added [here](https://github.com/sezzle/sezzle-js/blob/ac6bc8d3b51596f360dbe6aa2e62d1dbda0e704b/src/classBased/sezzleDOMFunctions.js#L255)? As I mentioned before, whenever we update a price in a price range product, we don't re-render the widget, so the `render` function is not called. Instead in the mutation callback (link above) replaces the content of the widget price. We should accordingly replace the modal content.
> 2. Please, add ; at the end of the sentences in the new codebase you added. This is not obligatory, but it seems to be the pattern in sezzle-js, so better stick to it.
> 3. I am a bit concerned about the number of adds vs deletions (+1,582 −306), and this is  even without any unit test added. What is the sezzle.js bundle size and the modal bundle size with all the updates?

Response to above:
1. I'm working on a change on top of your branch and the rendering logic will completely change. I will create a new MR for integration or would you be ok with me adding the changes to your branch?  
2. Will keep that in mind. 
3. The code base has grown since we have long term modal introduced in this version, along with its translation and styling. Modal size should be approx 90kb and not sure about sezzle-js since it is a work in progress(integrations on top of wid-779)

2021-12-30 00:15 UTC, gopida commented on modals/modals-3.0.2/modal-longterm.js
> +        const translation = new Translation().get(this.language)
When modal loads onclick, either standard or long term class is instantiated. So there will only be one instance of translation created per call.

2021-12-30 00:15 UTC, gopida commented on modals/modals-3.0.2/modal-longterm.js
> +        return paymentOptions
Addressed

2021-12-30 00:17 UTC, gopida commented on modals/modals-3.0.2/modal-longterm.js
> +        Array.prototype.forEach.call(paymentTerms, (option) =>  {
Thought `forEach` will have issues in IE11. 
Addressed.

2021-12-30 00:18 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    const standardModal = new StandardModal({language, theme})
Didn't want a long param in the constructor. Since its only 2 param now, modified to pass as param.

2021-12-30 00:51 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    const longTermModal = new LongTermModal({
I think is okay to have them separate, since they both have different properties and it is easy to maintain. We may add some more logic to it in future. In terms of bundle size in having an extra class, tried having both the logic in single class. It didn't make much difference.

2022-01-03 15:16 UTC, electrodrel commented on modals/modals-3.0.2/modal.js
> +    const language = document.modalLanguage || 'en'
I mean, does modal translations have any control on the language set of the sezzle-js? If, say, Italian language is added to sezzle-js, because a particular merchant  wants to support it, but the Italian translations are not added to the modal translation set, the value of the `const language = document.modalLanguage || 'en'` is `it-IT`, and, the result of  the `getTranslation` is `undefined`

2022-01-03 15:23 UTC, electrodrel commented on modals/modals-3.0.2/modal-longterm.js
> +        const translation = new Translation().get(this.language)
Well, I am not talking about calling `getContet` twice. I am saying, that once you call `getContent` for, say, long term modal, you create one instance of the `Translation` class. Then, inside `getContent`, you call `getPaymentTermDivs()` (line #51). Inside `getPaymentTermDivs` you create another instance of the `Translation` class at the line #11. Both instances are created with the same `language` argument, so I am not sure why we need two.

2022-01-03 15:26 UTC, electrodrel commented on modals/modals-3.0.2/modal-longterm.js
> +        Array.prototype.forEach.call(paymentTerms, (option) =>  {
We polyfill our code, so we generally don't need to care much about a specific browser support.

2022-01-03 15:38 UTC, electrodrel commented on modals/modals-3.0.2/modal.js
> +    return;
Why do we need `return` statements here and in the functions below?

2022-01-03 18:17 UTC, gopida commented on modals/modals-3.0.2/modal.js
> +    return;
Addressed

2022-01-03 18:18 UTC, gopida commented on modals/modals-3.0.2/modal-longterm.js
> +        const translation = new Translation().get(this.language)
Addressed

2022-01-03 20:33 UTC, electrodrel approved these changes

2022-01-04 19:54 UTC, aholdahl approved these changes

2022-01-04 23:05 UTC, merged